---
title: "PRACTICA 2"
author: ""
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, include=FALSE}
library(knitr)

```


```{r}
library(rockchalk)
library(nortest)
library(normtest)
library(moments)
library(car)
library(ggplot2)
library(dplyr)
```



```{r read}
surveyMentalHealth<-read.csv("survey.csv", sep=",",na.strings = "NA")
#Mostramos las primeras filas
head(surveyMentalHealth) 
```


```{r}
#Eliminación de las variables
surveyMentalHealth$Timestamp<-NULL
surveyMentalHealth$state<-NULL
surveyMentalHealth$comments<-NULL
#summary(surveyMentalHealth)
```

```{r}
colnames(surveyMentalHealth)
```

```{r str}
str(surveyMentalHealth) 
```

  
```{r }
#Número de fila del fichero. 
nrow(surveyMentalHealth)
```


```{r}
sapply(surveyMentalHealth,class)
```


```{r}
#En el momento de la lectura del fichero establecemos 
#que si se encuenta un valor perdido los asigne por NA (na.strings = "NA")
table(is.na(surveyMentalHealth$Age))
```

```{r}
table(is.na(surveyMentalHealth$Gender))
```

```{r}
table(is.na(surveyMentalHealth$Country ))
```

```{r}
table(is.na(surveyMentalHealth$self_employed))
```

```{r}
table(is.na(surveyMentalHealth$family_history))
```

```{r}
table(is.na(surveyMentalHealth$treatment))
```

```{r}
table(is.na(surveyMentalHealth$work_interfere))
```

```{r}
table(is.na(surveyMentalHealth$no_employees))
```

```{r}
table(is.na(surveyMentalHealth$remote_work))
```

```{r}
table(is.na(surveyMentalHealth$tech_company))
```

```{r}
table(is.na(surveyMentalHealth$benefits))
```

```{r}
table(is.na(surveyMentalHealth$care_options))
```

```{r}
table(is.na(surveyMentalHealth$ wellness_program))
```

```{r}
table(is.na(surveyMentalHealth$seek_help))
```

```{r}
table(is.na(surveyMentalHealth$anonymity))
```

```{r}
table(is.na(surveyMentalHealth$leave))
```

```{r}
table(is.na(surveyMentalHealth$mental_health_consequence))
```

```{r}
table(is.na(surveyMentalHealth$phys_health_consequence))
```

```{r}
table(is.na(surveyMentalHealth$coworkers))
```

```{r}
table(is.na(surveyMentalHealth$supervisor))
```

```{r}
table(is.na(surveyMentalHealth$mental_health_interview))
```

```{r}
table(is.na(surveyMentalHealth$phys_health_interview))
```

```{r}
table(is.na(surveyMentalHealth$mental_vs_physical))
```

```{r}
table(is.na(surveyMentalHealth$obs_consequence))
```


```{r}
surveyMentalHealth$Age[which(surveyMentalHealth$Age==0) ]

```

**Age**


```{r}
barplot(table(surveyMentalHealth$Age))
```



```{r}
datos_atipicos<-subset(surveyMentalHealth[1:1], surveyMentalHealth$Age<16 | surveyMentalHealth$Age>75)
datos_atipicos
```


```{r}
surveyMentalHealth_clean<-subset(surveyMentalHealth, surveyMentalHealth$Age>16 & surveyMentalHealth$Age<75)
nrow(surveyMentalHealth_clean)
```



```{r}
summary(surveyMentalHealth_clean$Age)
```

```{r}
boxplot(surveyMentalHealth_clean$Age)
```

```{r}
#Media Aritmetica 
Media_Age<-mean(surveyMentalHealth_clean$Age)
#Mediana
Mediana_Age<-median(surveyMentalHealth_clean$Age)
#Media Recortada
Media_Recortada_Age<-mean(surveyMentalHealth_clean$Age, trim=0.05)
#Desviación estándar
Desviacion_estandar_Age<-sd(surveyMentalHealth_clean$Age)
#Rango Intercuartilico (RIC)
RIC_Age<-IQR(surveyMentalHealth_clean$Age)
#Desviación Absoluta Respecto de la Mediana
Desviacion_Absoluta_Mediana_Age<-mad(surveyMentalHealth_clean$Age)
#Tabla 
kable(rbind(Media_Age,Mediana_Age,Media_Recortada_Age,
            Desviacion_estandar_Age,RIC_Age,
            Desviacion_Absoluta_Mediana_Age))
```
**Gender**


```{r}
levels(surveyMentalHealth_clean$Gender)
```


```{r}
surveyMentalHealth_clean$Gender<-as.character(surveyMentalHealth_clean$Gender)
surveyMentalHealth_clean$Gender<-replace(surveyMentalHealth_clean$Gender,surveyMentalHealth_clean$Gender=="Cis Female"|surveyMentalHealth_clean$Gender=="cis-female/femme"|surveyMentalHealth_clean$Gender=="f"|surveyMentalHealth_clean$Gender=="femail"|surveyMentalHealth_clean$Gender=="Femake"|surveyMentalHealth_clean$Gender=="female"|surveyMentalHealth_clean$Gender=="Female"|surveyMentalHealth_clean$Gender=="Female "|surveyMentalHealth_clean$Gender=="Female (cis)"|surveyMentalHealth_clean$Gender=="Female (trans)"|surveyMentalHealth_clean$Gender=="Woman"|surveyMentalHealth_clean$Gender=="woman","F")

surveyMentalHealth_clean$Gender<-replace(surveyMentalHealth_clean$Gender,surveyMentalHealth_clean$Gender=="Male"|surveyMentalHealth_clean$Gender=="male"|surveyMentalHealth_clean$Gender=="Cis Male"|surveyMentalHealth_clean$Gender=="m"|surveyMentalHealth_clean$Gender=="Mail"|surveyMentalHealth_clean$Gender=="Make"|surveyMentalHealth_clean$Gender=="male leaning androgynous"|surveyMentalHealth_clean$Gender=="Malr"|surveyMentalHealth_clean$Gender=="msle"|surveyMentalHealth_clean$Gender=="ostensibly male, unsure what that really means"|surveyMentalHealth_clean$Gender=="something kinda male?"|surveyMentalHealth_clean$Gender=="Androgyne"|surveyMentalHealth_clean$Gender=="cis male"|surveyMentalHealth_clean$Gender=="Cis Man"|surveyMentalHealth_clean$Gender=="Guy (-ish) ^_^"|surveyMentalHealth_clean$Gender=="maile"|surveyMentalHealth_clean$Gender=="Mal"|surveyMentalHealth_clean$Gender=="Male (CIS)"|surveyMentalHealth_clean$Gender=="Male-ish"|surveyMentalHealth_clean$Gender=="Man"|surveyMentalHealth_clean$Gender=="Male ","M")

surveyMentalHealth_clean$Gender<-replace(surveyMentalHealth_clean$Gender,surveyMentalHealth_clean$Gender=="A little about you"|surveyMentalHealth_clean$Gender=="Agender"|surveyMentalHealth_clean$Gender=="All"|surveyMentalHealth_clean$Gender=="Enby"|surveyMentalHealth_clean$Gender=="fluid"|surveyMentalHealth_clean$Gender=="Genderqueer"|surveyMentalHealth_clean$Gender=="Nah"|surveyMentalHealth_clean$Gender=="Neuter"|surveyMentalHealth_clean$Gender=="non-binary"|surveyMentalHealth_clean$Gender=="p"|surveyMentalHealth_clean$Gender=="queer"|surveyMentalHealth_clean$Gender=="queer/she/they"|surveyMentalHealth_clean$Gender=="Trans woman"|surveyMentalHealth_clean$Gender=="Trans-female",NA)

surveyMentalHealth_clean$Gender<-as.factor(surveyMentalHealth_clean$Gender)
```


```{r}
levels(surveyMentalHealth_clean$Gender)
```


```{r}
surveyMentalHealth_clean<-subset(surveyMentalHealth_clean, surveyMentalHealth_clean$Gender!="NA")
nrow(surveyMentalHealth_clean)
```



**Country**

```{r}
levels(surveyMentalHealth_clean$Country)
summary(surveyMentalHealth_clean$Country)
```

```{r}
barplot(table(surveyMentalHealth_clean$Country), 
        main="Paises")
``` 


**family_history**

```{r}
levels(surveyMentalHealth_clean$family_history)
summary(surveyMentalHealth_clean$family_history)

```

```{r}
barplot(table(surveyMentalHealth_clean$family_history), 
        main="Antecedentes familiares")
``` 
**treatment**

```{r}
levels(surveyMentalHealth_clean$treatment)
summary(surveyMentalHealth_clean$treatment)

```

```{r}
barplot(table(surveyMentalHealth_clean$treatment), 
        main="Ha sido tratado de alguna enfermedad mental")
``` 

**work_interfere**

```{r}
levels(surveyMentalHealth_clean$work_interfere)
summary(surveyMentalHealth_clean$work_interfere)

```

```{r}
barplot(table(surveyMentalHealth_clean$work_interfere), 
        main="La enfermendad mental interfiere en su trabajo")
``` 

**no_employees**
```{r}
levels(surveyMentalHealth_clean$no_employees)
summary(surveyMentalHealth_clean$no_employees)

```

```{r}
barplot(table(surveyMentalHealth_clean$no_employees), 
        main="Número de empleados de la compañia u organizacion")
``` 

**remote_work**
```{r}
levels(surveyMentalHealth_clean$remote_work)
summary(surveyMentalHealth_clean$remote_work)

```

```{r}
barplot(table(surveyMentalHealth_clean$remote_work), 
        main="Teletrabajo al menos el 50% del tiempo")
``` 

**tech_company**
```{r}
levels(surveyMentalHealth_clean$tech_company)
summary(surveyMentalHealth_clean$tech_company)

```

```{r}
barplot(table(surveyMentalHealth_clean$tech_company), 
        main="La Organización es Tecnologica")
``` 

**benefits**

```{r}
levels(surveyMentalHealth_clean$benefits)
summary(surveyMentalHealth_clean$benefits)

```

```{r}
barplot(table(surveyMentalHealth_clean$benefits), 
        main="La Organizacion provee de beneficios de salud Mental")
``` 

**care_options**
```{r}
levels(surveyMentalHealth_clean$care_options)
summary(surveyMentalHealth_clean$care_options)

```

```{r}
barplot(table(surveyMentalHealth_clean$care_options), 
        main="Conoce Opciones de cuidado mental de su compañia médica")
``` 

**wellness_program**
  
```{r}
levels(surveyMentalHealth_clean$wellness_program)

```
 
 
```{r}
summary (surveyMentalHealth_clean$wellness_program)

```
 

```{r}
barplot(table(surveyMentalHealth_clean$wellness_program), 
        main="Información del conocimiento de programas especificos")
```
**seek_help**
  
```{r}
levels(surveyMentalHealth_clean$seek_help)
```

 
 
```{r}
summary (surveyMentalHealth_clean$seek_help)

```


```{r}
barplot(table(surveyMentalHealth_clean$seek_help), 
        main="Información de recursos y ayuda desde la organización")
```

**anonymity**
  
```{r}
levels(surveyMentalHealth_clean$anonymity)
```

 
```{r}
summary (surveyMentalHealth_clean$anonymity)

```

```{r}
barplot(table(surveyMentalHealth_clean$anonymity), 
        main="Privacidad de beneficios sobre enfermedades mentales")
``` 
**leave**
  
```{r}
levels(surveyMentalHealth_clean$leave)
```


 
```{r}
summary (surveyMentalHealth_clean$leave)

```

```{r }
barplot(table(surveyMentalHealth_clean$leave), 
        main="Posibilidad de baja en enfermedades mentales")
``` 
**mental_health_consequence**
  
```{r}
levels(surveyMentalHealth_clean$mental_health_consequence)
```


 
```{r}
summary (surveyMentalHealth_clean$mental_health_consequence)

```
  


```{r}
barplot(table(surveyMentalHealth_clean$mental_health_consequence), 
        main="Consecuencias por hablar de salud mental")
``` 

**phys_health_consequence**

```{r}
levels(surveyMentalHealth_clean$phys_health_consequence)
```

```{r}
summary (surveyMentalHealth_clean$phys_health_consequence)

```


```{r}
barplot(table(surveyMentalHealth_clean$phys_health_consequence), 
        main="Consecuencias por hablar de salud física")
``` 

**coworkers**
   
```{r}
levels(surveyMentalHealth_clean$coworkers)
```

```{r}
summary (surveyMentalHealth_clean$coworkers)

```


```{r}
barplot(table(surveyMentalHealth_clean$mental_health_consequence), 
        main="Hablaria de salud mental con compañeros")
``` 

**supervisor**
```{r}
levels(surveyMentalHealth_clean$supervisor)
```

```{r}
summary (surveyMentalHealth_clean$supervisor)

```

```{r}
barplot(table(surveyMentalHealth_clean$supervisor), 
        main="Hablaria de salud mental con su jefe")
``` 

**mental_health_interview**

```{r}
levels(surveyMentalHealth_clean$mental_health_interview)
```

```{r}
summary (surveyMentalHealth_clean$mental_health_interview)

```


```{r}
barplot(table(surveyMentalHealth_clean$mental_health_interview), 
        main="Hablaria de salud mental en una entrevista laboral")
``` 
**phys_health_interview**
```{r}
levels(surveyMentalHealth_clean$phys_health_interview)
```

```{r}
summary (surveyMentalHealth_clean$phys_health_interview)

```

```{r}
barplot(table(surveyMentalHealth_clean$mental_health_interview), 
        main="Hablaria de salud física en una entrevista laboral")
``` 
**mental_vs_physical**

```{r}
levels(surveyMentalHealth_clean$mental_vs_physical)
```

```{r}
summary (surveyMentalHealth_clean$mental_vs_physical)

```


```{r }
barplot(table(surveyMentalHealth_clean$mental_vs_physical), 
        main="Importacia en la Organizacion de la salud mental sobre la física")
``` 

**obs_consequence**

```{r}
levels(surveyMentalHealth_clean$obs_consequence)
```

```{r}
summary (surveyMentalHealth_clean$obs_consequence)

```


```{r}
barplot(table(surveyMentalHealth_clean$obs_consequence), 
        main="Consecuencias laboral por padecer enfermedad mental ")
``` 


```{r}
#Gráfica comparativa 1
    par(mfrow=c(1,2))
    barplot(table(surveyMentalHealth_clean$mental_health_interview), 
            main="Mención mental en entrevista laboral")
    barplot(table(surveyMentalHealth_clean$phys_health_interview), 
            main="Mención física en entrevista laboral")
```

```{r}
#Gráfica comparativa 2
    par(mfrow=c(1,2))
    barplot(table(surveyMentalHealth_clean$mental_health_consequence), 
            main="Mental:¿consecuencias negativas?")
    barplot(table(surveyMentalHealth_clean$phys_health_consequence), 
            main="Física:¿consecuencias negativas?")
```



```{r}
#Conjunto de valores de la variable Edad que consideran que la organización da mayor importancia a la salud mental vs salud fisica.
Age_Mental<-subset(surveyMentalHealth_clean$Age, surveyMentalHealth_clean$mental_vs_physical=="Yes")
```

```{r}
Age_Fisica<-subset(surveyMentalHealth_clean$Age, surveyMentalHealth_clean$mental_vs_physical=="No")
```


```{r}
#Calculo Media
mean(Age_Mental)
mean(Age_Fisica)
```

```{r}
#Calculo Mediana
median(Age_Mental)
median(Age_Fisica)
```

```{r}
#Sumario de los cinco números (Mínimo, Q1, Mediana, Q3, Maximo)
fivenum(Age_Mental)
```

```{r}
#Sumario de los cinco números (Mínimo, Q1, Mediana, Q3, Maximo)
fivenum(Age_Fisica)
```

```{r}
#Diagrama de caja (Boxplot)
boxplot(Age_Mental, main="Box Plot Age Salud Mental")
```


```{r}
#Diagrama de caja (Boxplot)
boxplot(Age_Fisica, main="Box Plot Age Salud Fisica")
```

```{r}
#Calculamos el numero de intervalor
k_Age_Mental<- round(sqrt(length(Age_Mental)))
k_Age_Mental
```

```{r}
#Calculamos el numero de intervalor
k_Age_Fisica<- round(sqrt(length(Age_Fisica)))
k_Age_Fisica
```

```{r}
hist(Age_Mental ,main="Edad individuos Organizacion mas valor a la Salud Mental",
     breaks=k_Age_Mental, col="blue")
```

```{r}
hist(Age_Fisica ,main="Edad individuos con Organizacion mas valor a la Salud Fisica",
     breaks=k_Age_Fisica, col="blue")
```


```{r}
hh_Age_Mental<-hist(Age_Mental ,main="Edad individuos con Organizacion mas valor a la Salud Mental",
     breaks=k_Age_Mental, col="blue")
hh_Age_Mental
```

```{r}
hh_Age_Fisica<-hist(Age_Fisica ,main="Edad individuos con Organizacion mas valor a la Salud Fisica",
     breaks=k_Age_Fisica, col="blue")
hh_Age_Fisica
```


```{r}
#Calculo de la función de densidad
den_Age_Mental<- density(Age_Mental)
plot(den_Age_Mental ,main="Edad Individuos con Organización mas valor a la Salud Mental")
polygon(den_Age_Mental , col="blue", border="red")

```

```{r}
#Calculo de la función de densidad
den_Age_Fisica<- density(Age_Fisica)
plot(den_Age_Fisica ,main="Edad Individuos con Organización mas valor a la Salud Fisica")
polygon(den_Age_Fisica , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_Mental ,main="Edad individuos con Organización mas valor a la Salud Mental",
     col="gold",freq=FALSE)
lines(den_Age_Mental,col="blue",lwd=4)
```

```{r}
#Superposición de las gráficas
hist(Age_Fisica ,main="Edad Individuos con Organización más valor a la Salud Fisica",
     col="gold",freq=FALSE)
lines(den_Age_Mental ,col="blue",lwd=4)
```

```{r}
qqnorm(Age_Mental)
qqline(Age_Mental)
```

```{r}
qqnorm(Age_Fisica)
qqline(Age_Fisica)
```


```{r}
ks.test(x=Age_Mental,"pnorm", mean(Age_Mental), sd(Age_Mental))
```

```{r}
ks.test(Age_Fisica,"pnorm", mean(Age_Fisica), sd(Age_Fisica))
```


```{r}

lillie.test((x=Age_Mental))
```

```{r}

lillie.test((x=Age_Fisica))
```


```{r}
jb.norm.test(x=Age_Mental)
```

```{r}
jb.norm.test(x=Age_Fisica)
```
 
```{r}
Age_Mental_Trans<-(sqrt(sqrt(1/Age_Mental)))
```

```{r}
#Calculo de la función de densidad
den_Age_Mental_Trans<- density(Age_Mental_Trans)
plot(den_Age_Mental_Trans ,main="Densidad de la edad de los individuos observados")
polygon(den_Age_Mental_Trans , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_Mental_Trans ,main="Histograma y densidad del valor de la edad de los individuos observados",
     col="gold",freq=FALSE)
lines(den_Age_Mental_Trans ,col="blue",lwd=4)
```

```{r}
qqnorm(Age_Mental_Trans)
qqline(Age_Mental_Trans)
```

```{r}

lillie.test((x=Age_Mental_Trans))
```

```{r}
Age_Fisica_Trans<-(sqrt(sqrt(1/Age_Fisica)))
```

```{r}
#Calculo de la función de densidad
den_Age_Fisica_Trans<- density(Age_Fisica_Trans)
plot(den_Age_Fisica_Trans ,main="Densidad de la edad de los individuos observados")
polygon(den_Age_Fisica_Trans , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_Fisica_Trans ,main="Histograma y densidad del valor de la edad de los individuos observados",
     col="gold",freq=FALSE)
lines(den_Age_Fisica_Trans ,col="blue",lwd=4)
```


```{r}
qqnorm(Age_Fisica_Trans)
qqline(Age_Fisica_Trans)
```

```{r}

lillie.test((x=Age_Fisica_Trans))
```



```{r}
bartlett.test(list(Age_Mental,Age_Fisica))
```



```{r}
ggplot(surveyMentalHealth_clean, aes(x = mental_vs_physical, y = Age, colour =mental_vs_physical)) + geom_boxplot() + theme_bw()
```


```{r}
#Conjunto de valores de la variable Edad que consideran que la organización da mayor importancia a la salud mental vs salud fisica.
Age_Tratamiento<-subset(surveyMentalHealth_clean$Age, surveyMentalHealth_clean$treatment=="Yes")
```

```{r}
Age_NTratamiento<-subset(surveyMentalHealth_clean$Age, surveyMentalHealth_clean$treatment=="No")
```


```{r}
#Calculo Media
mean(Age_Tratamiento)
mean(Age_NTratamiento)
```

```{r}
#Calculo Mediana
median(Age_Tratamiento)
median(Age_NTratamiento)
```

```{r}
#Sumario de los cinco números (Mínimo, Q1, Mediana, Q3, Maximo)
fivenum(Age_Tratamiento)
```

```{r}
#Sumario de los cinco números (Mínimo, Q1, Mediana, Q3, Maximo)
fivenum(Age_NTratamiento)
```

Gráfico de Boxplot
```{r}
#Diagrama de caja (Boxplot)
boxplot(Age_Tratamiento, main="Box Plot Age Con Tratamiento")
```


```{r}
#Diagrama de caja (Boxplot)
boxplot(Age_NTratamiento, main="Box Plot Age Sin Tratamiento")
```

 
```{r}
#Calculamos el numero de intervalor
k_Age_Tratamiento<- round(sqrt(length(Age_Tratamiento)))
k_Age_Tratamiento
```

```{r}
#Calculamos el numero de intervalor
k_Age_NTratamiento<- round(sqrt(length(Age_NTratamiento)))
k_Age_NTratamiento
```

```{r}
hist(Age_Tratamiento ,main="Edad individuos con Tratamiento Salud Mental",
     breaks=k_Age_Tratamiento, col="blue")
```

```{r}
hist(Age_NTratamiento ,main="Edad individuos sin Tratamiento Salud Mental",
     breaks=k_Age_NTratamiento, col="blue")
```


```{r}
hh_Age_Tratamiento<-hist(Age_Tratamiento ,main="Edad individuos con Tratamiento Salud Mental",
     breaks=k_Age_Tratamiento, col="blue")
hh_Age_Tratamiento
```

```{r}
hh_Age_NTratamiento<-hist(Age_NTratamiento ,main="Edad individuos sin Tratamiento Salud Mental",
     breaks=k_Age_NTratamiento, col="blue")
hh_Age_NTratamiento
```


```{r}
#Calculo de la función de densidad
den_Age_Tratamiento<- density(Age_Tratamiento)
plot(den_Age_Tratamiento ,main="Densidad de la edad de los individuos con Tratamiento")
polygon(den_Age_Tratamiento , col="blue", border="red")

```

```{r}
#Calculo de la función de densidad
den_Age_NTratamiento<- density(Age_NTratamiento)
plot(den_Age_NTratamiento ,main="Densidad de la edad de los individuos observados sin Tratamiento")
polygon(den_Age_NTratamiento , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_Tratamiento ,main="Edad individuos con Tratamiento de  Salud Mental",
     col="gold",freq=FALSE)
lines(den_Age_Tratamiento,col="blue",lwd=4)
```

```{r}
#Superposición de las gráficas
hist(Age_NTratamiento ,main="Edad Individuos sin tratamiento de Salud Mental",
     col="gold",freq=FALSE)
lines(den_Age_NTratamiento ,col="blue",lwd=4)
```

```{r}
qqnorm(Age_Tratamiento)
qqline(Age_Tratamiento)
```

```{r}
qqnorm(Age_NTratamiento)
qqline(Age_NTratamiento)
```

```{r}
ks.test(x=Age_Tratamiento,"pnorm", mean(Age_Tratamiento), sd(Age_Tratamiento))
```

```{r}
ks.test(Age_NTratamiento,"pnorm", mean(Age_NTratamiento), sd(Age_NTratamiento))
```


```{r}

lillie.test((x=Age_Tratamiento))
```

```{r}

lillie.test((x=Age_NTratamiento))
```


```{r}
jb.norm.test(x=Age_Tratamiento)
```

```{r}
jb.norm.test(x=Age_NTratamiento)
```


```{r}
Age_Tratamiento_Trans<-((sqrt(1/Age_Tratamiento)))
```

```{r}
#Calculo de la función de densidad
den_Age_Tratamiento_Trans<- density(Age_Tratamiento_Trans)
plot(den_Age_Tratamiento_Trans ,main="Densidad de la edad de los individuos observados")
polygon(den_Age_Tratamiento_Trans , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_Tratamiento_Trans ,main="Histograma y densidad del valor de la edad de los individuos observados",
     col="gold",freq=FALSE)
lines(den_Age_Tratamiento_Trans ,col="blue",lwd=4)
```

```{r}
qqnorm(Age_Tratamiento_Trans)
qqline(Age_Tratamiento_Trans)
```

```{r}

lillie.test((x=Age_Tratamiento_Trans))
```


```{r}
Age_NTratamiento_Trans<-((sqrt(1/Age_NTratamiento)))
```

```{r}
#Calculo de la función de densidad
den_Age_NTratamiento_Trans<- density(Age_NTratamiento_Trans)
plot(den_Age_NTratamiento_Trans ,main="Densidad de la edad de los individuos sin Tratamiento")
polygon(den_Age_NTratamiento_Trans , col="blue", border="red")

```

```{r}
#Superposición de las gráficas
hist(Age_NTratamiento_Trans ,main="Histograma y densidad del valor de la edad de los individuos sin Tratamiento",
     col="gold",freq=FALSE)
lines(den_Age_NTratamiento_Trans ,col="blue",lwd=4)
```



```{r}
qqnorm(Age_NTratamiento_Trans)
qqline(Age_NTratamiento_Trans)
```

```{r}

lillie.test((x=Age_NTratamiento_Trans))
```


```{r}
bartlett.test(list(Age_Tratamiento,Age_NTratamiento))
```


```{r}
ggplot(surveyMentalHealth_clean, aes(x = treatment, y = Age, colour =treatment)) + geom_boxplot() + theme_bw()
```


```{r}
fit=lm(Age~ treatment, surveyMentalHealth_clean)
aov(fit)
```

```{r}
summary(aov(fit))
```



```{r}
fit2=lm(Age~ mental_vs_physical, surveyMentalHealth_clean)
aov(fit2)
```

```{r}
summary(aov(fit2))
```




```{r}
#Se guardan los cambios realizados en el fichero rodriguez_inmuebles_clean.csv
write.csv(surveyMentalHealth_clean, file="survey_clean.csv")
```


